name: Build and Release

on:
  push:
    branches:
      - build

jobs:
  build:
    name: Build and Package Binary
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build firmware
        uses: esphome/build-action@v1
        with:
          yaml_file: script.yaml

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Release of version ${{ github.ref }}
          draft: false
          prerelease: true

      - name: Upload binary
        uses: actions/upload-release-asset@v1
        with:
          asset_path: ./my_configuration.bin
          asset_name: my_configuration.bin
          asset_content_type: application/octet-stream
          tag_name: ${{ github.ref }}
